"""Render a real PNG texture for a console's screen/faceplate (a tabbed UI
with a button grid, matching the look of a real medical/industrial control
touchscreen) using PIL -- so a generated console's screen actually shows
readable tab labels and button text instead of a flat emissive color.

Why this exists: a first console generated by this skill (a CT/MRI table
pendant) was directly compared against its real reference photo and
honestly found NOT to look similar -- no labels, no icons, a flat dark box
standing in for the screen, uniform gray-metal material instead of white/
cream plastic with blue accent buttons. Webots' Display node is for LIVE,
programmatically-drawn content (black until something draws to it at
runtime) -- it doesn't give a good default "idle" appearance for a static
scene or a screenshot-based comparison. A pre-rendered ImageTexture applied
to the screen's own Shape gives a real, readable look immediately, with the
Display device still present alongside it for genuine live content later.

IMPORTANT -- width_px/height_px should each be a power of two (256, 512,
1024...), and their ratio should match the screen's width_m/height_m ratio.
Confirmed directly: Webots silently rescales a non-power-of-two texture to
the nearest power of two on load (a 480x320 PNG became 512x512), stretching
a rectangular UI into a square and distorting every label -- there is no
warning-free way around this, only choosing dimensions that are already a
power of two so no rescale happens at all.

Usage:
    python generate_faceplate_texture.py ui_spec.json --out screen.png

ui_spec.json format:
{
  "width_px": 512, "height_px": 256,
  "background_color": [10, 20, 45],
  "tabs": [{"label": "Exam", "active": true}, {"label": "Post-trait"}, ...],
  "button_rows": [
    [{"label": "Prog\nd'exam"}, {"label": "Coro FD\n7.5f/s"}, null, ...],
    ...
  ]
}
A `null` entry in a button row leaves that grid cell empty (matches a real
panel's uneven layout instead of forcing a perfectly full grid).
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


def _font(size: int) -> ImageFont.FreeTypeFont:
    try:
        return ImageFont.truetype("arial.ttf", size)
    except Exception:
        return ImageFont.load_default()


def render(spec: dict) -> Image.Image:
    width = spec.get("width_px", 480)
    height = spec.get("height_px", 320)
    bg = tuple(spec.get("background_color", [12, 20, 45]))
    img = Image.new("RGB", (width, height), bg)
    draw = ImageDraw.Draw(img)

    tabs = spec.get("tabs", [])
    tab_h = int(height * 0.09) if tabs else 0
    if tabs:
        tab_w = width / len(tabs)
        for i, tab in enumerate(tabs):
            x0, x1 = i * tab_w, (i + 1) * tab_w
            active = tab.get("active", False)
            fill = (235, 235, 240) if active else (30, 60, 110)
            text_color = (10, 10, 20) if active else (200, 210, 230)
            draw.rectangle([x0 + 1, 0, x1 - 1, tab_h - 1], fill=fill)
            f = _font(max(10, tab_h // 3))
            label = tab.get("label", "")
            bbox = draw.textbbox((0, 0), label, font=f)
            tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
            draw.text((x0 + (tab_w - tw) / 2, (tab_h - th) / 2 - bbox[1]), label, fill=text_color, font=f)

    rows = spec.get("button_rows", [])
    if rows:
        grid_top = tab_h + 4
        grid_h = height - grid_top - 4
        row_h = grid_h / len(rows)
        max_cols = max(len(row) for row in rows)
        col_w = width / max_cols
        f = _font(max(9, int(row_h * 0.22)))
        for r, row in enumerate(rows):
            for c, cell in enumerate(row):
                if cell is None:
                    continue
                x0, x1 = c * col_w + 2, (c + 1) * col_w - 2
                y0, y1 = grid_top + r * row_h + 2, grid_top + (r + 1) * row_h - 2
                fill = tuple(cell.get("color", [225, 228, 235]))
                draw.rectangle([x0, y0, x1, y1], fill=fill, outline=(120, 125, 140))
                label = cell.get("label", "")
                lines = label.split("\n")
                text_color = tuple(cell.get("text_color", [20, 20, 30]))
                line_h = f.size + 2
                total_h = line_h * len(lines)
                start_y = y0 + ((y1 - y0) - total_h) / 2
                for li, line in enumerate(lines):
                    bbox = draw.textbbox((0, 0), line, font=f)
                    tw = bbox[2] - bbox[0]
                    draw.text((x0 + ((x1 - x0) - tw) / 2, start_y + li * line_h), line, fill=text_color, font=f)

    return img


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("ui_spec_path")
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    spec = json.loads(Path(args.ui_spec_path).read_text(encoding="utf-8"))
    img = render(spec)
    img.save(args.out)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
